[2025-09-02T21:16:15.003+0800] INFO - local_task_job_runner.py:123 - _execute() - ::group::Pre task execution logs
[2025-09-02T21:16:15.146+0800] INFO - taskinstance.py:2613 - are_dependencies_met() - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: example_parallel_dag.task3 scheduled__2025-09-02T12:00:00+00:00 [queued]>
[2025-09-02T21:16:15.228+0800] INFO - taskinstance.py:2613 - are_dependencies_met() - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: example_parallel_dag.task3 scheduled__2025-09-02T12:00:00+00:00 [queued]>
[2025-09-02T21:16:15.229+0800] INFO - taskinstance.py:2866 - _check_and_change_state_before_execution() - Starting attempt 1 of 2
[2025-09-02T21:16:15.421+0800] INFO - taskinstance.py:2889 - _check_and_change_state_before_execution() - Executing <Task(PythonOperator): task3> on 2025-09-02 12:00:00+00:00
[2025-09-02T21:16:15.499+0800] INFO - standard_task_runner.py:72 - _start_by_fork() - Started process 250 to run task
[2025-09-02T21:16:15.522+0800] INFO - standard_task_runner.py:104 - _start_by_fork() - Running: ['***', 'tasks', 'run', 'example_parallel_dag', 'task3', 'scheduled__2025-09-02T12:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/example_parallel_dag.py', '--cfg-path', '/tmp/tmpblft_c5a']
[2025-09-02T21:16:15.536+0800] INFO - standard_task_runner.py:105 - _start_by_fork() - Job 7: Subtask task3
[2025-09-02T21:16:16.259+0800] INFO - task_command.py:467 - task_run() - Running <TaskInstance: example_parallel_dag.task3 scheduled__2025-09-02T12:00:00+00:00 [running]> on host a246a11defc8
[2025-09-02T21:16:17.951+0800] INFO - taskinstance.py:3132 - _execute_task_with_callbacks() - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-team' AIRFLOW_CTX_DAG_ID='example_parallel_dag' AIRFLOW_CTX_TASK_ID='task3' AIRFLOW_CTX_EXECUTION_DATE='2025-09-02T12:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-02T12:00:00+00:00'
[2025-09-02T21:16:17.975+0800] INFO - taskinstance.py:731 - _execute_callable() - ::endgroup::
[2025-09-02T21:16:18.114+0800] INFO - logging_mixin.py:190 - _propagate_log() - Task task3 開始執行...
[2025-09-02T21:16:25.131+0800] INFO - logging_mixin.py:190 - _propagate_log() - Task task3 執行完成！
[2025-09-02T21:16:25.132+0800] INFO - python.py:240 - execute() - Done. Returned value was: None
[2025-09-02T21:16:25.203+0800] INFO - taskinstance.py:340 - _run_raw_task() - ::group::Post task execution logs
[2025-09-02T21:16:25.204+0800] INFO - taskinstance.py:352 - _run_raw_task() - Marking task as SUCCESS. dag_id=example_parallel_dag, task_id=task3, run_id=scheduled__2025-09-02T12:00:00+00:00, execution_date=20250902T120000, start_date=20250902T131615, end_date=20250902T131625
[2025-09-02T21:16:25.494+0800] INFO - local_task_job_runner.py:266 - handle_task_exit() - Task exited with return code 0
[2025-09-02T21:16:25.586+0800] INFO - standard_task_runner.py:217 - _read_task_utilization() - Process not found (most likely exited), stop collecting metrics
[2025-09-02T21:16:25.627+0800] INFO - local_task_job_runner.py:245 - _execute() - ::endgroup::
