[2025-09-02T21:16:15.006+0800] INFO - local_task_job_runner.py:123 - _execute() - ::group::Pre task execution logs
[2025-09-02T21:16:15.199+0800] INFO - taskinstance.py:2613 - are_dependencies_met() - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: example_parallel_dag.task2 scheduled__2025-09-02T12:00:00+00:00 [queued]>
[2025-09-02T21:16:15.326+0800] INFO - taskinstance.py:2613 - are_dependencies_met() - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: example_parallel_dag.task2 scheduled__2025-09-02T12:00:00+00:00 [queued]>
[2025-09-02T21:16:15.327+0800] INFO - taskinstance.py:2866 - _check_and_change_state_before_execution() - Starting attempt 1 of 2
[2025-09-02T21:16:15.592+0800] INFO - taskinstance.py:2889 - _check_and_change_state_before_execution() - Executing <Task(PythonOperator): task2> on 2025-09-02 12:00:00+00:00
[2025-09-02T21:16:15.705+0800] INFO - standard_task_runner.py:104 - _start_by_fork() - Running: ['***', 'tasks', 'run', 'example_parallel_dag', 'task2', 'scheduled__2025-09-02T12:00:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/example_parallel_dag.py', '--cfg-path', '/tmp/tmp89hedfnl']
[2025-09-02T21:16:15.716+0800] INFO - standard_task_runner.py:105 - _start_by_fork() - Job 8: Subtask task2
[2025-09-02T21:16:15.691+0800] INFO - standard_task_runner.py:72 - _start_by_fork() - Started process 258 to run task
[2025-09-02T21:16:16.235+0800] INFO - task_command.py:467 - task_run() - Running <TaskInstance: example_parallel_dag.task2 scheduled__2025-09-02T12:00:00+00:00 [running]> on host a246a11defc8
[2025-09-02T21:16:17.921+0800] INFO - taskinstance.py:3132 - _execute_task_with_callbacks() - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-team' AIRFLOW_CTX_DAG_ID='example_parallel_dag' AIRFLOW_CTX_TASK_ID='task2' AIRFLOW_CTX_EXECUTION_DATE='2025-09-02T12:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-02T12:00:00+00:00'
[2025-09-02T21:16:17.924+0800] INFO - taskinstance.py:731 - _execute_callable() - ::endgroup::
[2025-09-02T21:16:18.269+0800] INFO - logging_mixin.py:190 - _propagate_log() - Task task2 開始執行...
[2025-09-02T21:16:25.283+0800] INFO - logging_mixin.py:190 - _propagate_log() - Task task2 執行完成！
[2025-09-02T21:16:25.285+0800] INFO - python.py:240 - execute() - Done. Returned value was: None
[2025-09-02T21:16:25.360+0800] INFO - taskinstance.py:340 - _run_raw_task() - ::group::Post task execution logs
[2025-09-02T21:16:25.361+0800] INFO - taskinstance.py:352 - _run_raw_task() - Marking task as SUCCESS. dag_id=example_parallel_dag, task_id=task2, run_id=scheduled__2025-09-02T12:00:00+00:00, execution_date=20250902T120000, start_date=20250902T131615, end_date=20250902T131625
[2025-09-02T21:16:25.563+0800] INFO - local_task_job_runner.py:266 - handle_task_exit() - Task exited with return code 0
[2025-09-02T21:16:25.723+0800] INFO - local_task_job_runner.py:245 - _execute() - ::endgroup::
[2025-09-02T21:16:25.830+0800] INFO - standard_task_runner.py:217 - _read_task_utilization() - Process not found (most likely exited), stop collecting metrics
